export const GET_LIST_TAISAN = "GET_LIST_TAISAN";
export const GET_DETAIL_TAISAN = "GET_DETAIL_TAISAN";
export const DELETE_TAISAN = "DELETE_TAISAN";
export const ADD_TAISAN = "ADD_TAISAN";
export const PATCH_TAISAN = "PATCH_TAISAN";




